- name: Check if systemd.unified_cgroup_hierarchy=0 is in /proc/cmdline
  shell: "grep 'systemd.unified_cgroup_hierarchy=0' /proc/cmdline"
  register: unified_cgroup_hierarchy
  ignore_errors: true
  failed_when: false

- block:
  - name: Append systemd.unified_cgroup_hierarchy=0 to GRUB_CMDLINE_LINUX
    shell: |
      GRUB_FILE="/etc/default/grub"
      SEARCH_PATTERN="^GRUB_CMDLINE_LINUX="
      APPEND_TEXT="systemd.unified_cgroup_hierarchy=0 "

      if ! grep -q "systemd.unified_cgroup_hierarchy=0" "$GRUB_FILE"; then
          sed -i.bak.$(date +%Y%m%d-%H%M%S) "/$SEARCH_PATTERN/s/\"/& $APPEND_TEXT/" "$GRUB_FILE"
      fi
    args:
      executable: /bin/bash
    register: grub_update

  - name: Update GRUB
    command: update-grub

  - name: Check is need manual reboot to disable unified cgroup hierarchy
    fail:
      msg: "GRUB updated, Please reboot to disable cgroup hierarchy and run install script again"
    when: is_controller_node|default(false)|bool == true

  - name: "Reboot the system because GRUB updated. You can rerun this script when system running"
    ansible.builtin.reboot:

  - name: Wait for the system to become available
    wait_for_connection:
      timeout: 900

  when:
  - unified_cgroup_hierarchy.rc != 0
