- name: Check kubelet if init
  shell: test -f /etc/kubernetes/kubelet.conf
  register: kubelet_result
  ignore_errors: yes
  changed_when: false
  failed_when: false

- block:
  - name: "Sync /etc/sysconfig/kubelet"
    copy:
      src: etc_sysconfig_kubelet
      dest: /etc/sysconfig/kubelet
    become: true

  - name: "Restart kubelet"
    systemd:
      name: kubelet
      daemon_reload: yes
      state: restarted
    become: true
  when:
  - is_centos_based is defined
  - kubelet_result.rc == 0
