# Default values for cloudpods.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

createCRD: true

operator:
  replicaCount: 1
  syncUser: true
  disableNodeSelectorController: true
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  - key: node-role.kubernetes.io/controlplane
    effect: NoSchedule
  affinity: {}

  image:
    repository: "registry.cn-beijing.aliyuncs.com/yunion/onecloud-operator"
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v3.11.6"

  imagePullSecrets: []

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

localPathCSI:
  # 根据 k8s 集群的 CSI 部署情况，选择是否要部署默认的 local-path CSI
  # 如果 k8s 集群已经有稳定的 CSI ，就可以设置这个值为 false ，不部署该组件
  enabled: true
  helperPod:
    image: registry.cn-beijing.aliyuncs.com/yunionio/busybox:1.35.0
    pullPolicy: IfNotPresent
  image:
    # repository: "registry.cn-beijing.aliyuncs.com/yunion/local-path-provisioner"
    pullPolicy: IfNotPresent
    # tag: "v0.0.22"

cluster:
  mysql:
    # 外部 mysql 地址
    host: 1.2.3.4
    # 外部 mysql 端口
    port: 3306
    # 外部 mysql 用户，需要用具备 root 权限的用户，因为 cloudpods operator 会为其他服务创建数据库用户
    user: root
    # 外部 mysql 密码
    password: your-db-password
    statefulset:
      # 生产环境部署这里需要设置成 false ，不然会在 k8s 集群里面部署一个 mysql ，然后连接使用这个 statefulset mysql
      enabled: false
      image:
        repository: "registry.cn-beijing.aliyuncs.com/yunionio/mariadb"
        pullPolicy: IfNotPresent
        tag: "10.5.19"
      persistence:
        storageClass: ""
        accessMode: ReadWriteOnce
        size: 500Gi
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/controlplane
        effect: NoSchedule
  # Overrides the image tag whose default is the chart appVersion.
  version: "v3.11.6"
  # productVersion choose from:
  # - CMP
  # - FullStack
  # - Edge
  productVersion: CMP
  # disableResourceManagement disable container cgroup resource limits and requests
  disableResourceManagement: false
  # imageRepository defines default image registry
  imageRepository: registry.cn-beijing.aliyuncs.com/yunion
  # publicEndpoint is upstream ingress virtual ip address or DNS domain
  # 集群外部可访问的域名或者 ip 地址
  publicEndpoint: foo.bar.com
  # edition choose from:
  # - ce: community edition
  # - ee: enterprise edition
  # 选择部署 ce(开源) 或者 ee(企业) 版本
  edition: ce
  # storageClass for stateful component
  # 有状态服务使用的 storageClass，如果不设置就会使用 local-path CSI
  # 这个可根据 k8s 集群情况自行调节
  storageClass: ""
  ansibleserver:
    service:
      # 指定服务暴露的 nodePort，如果和集群已有服务冲突，可以修改
      nodePort: 30890
  apiGateway:
    apiService:
      nodePort: 30300
    wsService:
      nodePort: 30443
  autoupdate:
    service:
      nodePort: 30981
  # baremetal agent component spec
  baremetalagent:
    disable: true
    requests:
      storage: 100G
  cloudevent:
    service:
      nodePort: 30892
  cloudid:
    service:
      nodePort: 30893
  cloudnet:
    service:
      nodePort: 30891
  cloudproxy:
    service:
      nodePort: 30882
  devtool:
    service:
      nodePort: 30997
  # glance image component spec
  glance:
    service:
      nodePort: 30292
    requests:
      storage: 100G
  # influxdb component spec
  influxdb:
    service:
      nodePort: 30086
    requests:
      storage: 100G
  itsm:
    service:
      nodePort: 30595
  keystone:
    adminService:
      nodePort: 30357
    publicService:
      nodePort: 30500
  kubeserver:
    service:
      nodePort: 30442
  logger:
    service:
      nodePort: 30999
  # meter component spec
  meter:
    service:
      nodePort: 30909
    requests:
      storage: 25G
  monitor:
    service:
      nodePort: 30093
  onecloudServiceOperator:
    disable: true
    service:
      nodePort: 30885
  regionServer:
    service:
      nodePort: 30888
  report:
    service:
      nodePort: 30967
  s3gateway:
    service:
      nodePort: 30884
  scheduledtask:
    service:
      nodePort: 30978
  scheduler:
    service:
      nodePort: 30887
  suggestion:
    service:
      nodePort: 30987
  webconsole:
    service:
      nodePort: 30899
  yunionagent:
    service:
      nodePort: 30898
  yunionconf:
    service:
      nodePort: 30889

# 设置 ingress
ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - paths:
        - path: /
          pathType: ImplementationSpecific
      host: ""
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
