- block:

  - name: generate clickhouse spec conf
    template:
      src: clickhouse.spec.j2
      dest: /tmp/clickhouse.spec.yaml

  - name: Apply modifications for clickhouse
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
    shell: |
      kubectl patch onecloudclusters -n onecloud default --patch "$(cat /tmp/clickhouse.spec.yaml)" --type merge
      for i in autoupdate cloudevent glance keystone region kubeserver logger meter monitor notify webconsole
      do
        kubectl delete configmap -n onecloud default-$i
        kubectl rollout restart deployment -n onecloud default-$i
      done

      sleep 30

      # check all services that use clickhouse
      for i in autoupdate cloudevent glance keystone region kubeserver logger meter monitor notify webconsole
      do
        kubectl -n onecloud get configmap default-$i -o yaml | grep -qP '^\s+clickhouse: tcp'
      done
    args:
      executable: /bin/bash
    retries: 10
    register: clickhouse_result
    delay: 30
    ignore_errors: true
    become: yes
    until: clickhouse_result.rc == 0

  - name: clean tmp files
    shell: |
      rm -f /tmp/clickhouse.spec.yaml

  when:
  - offline_data_path is defined
  - offline_data_path | length > 0
  - (is_centos_x86 | default(false) | bool == true) or (is_openeuler_x86 | default(false) | bool == true)
  - ch_password | default('') | length > 0
